// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-8d96pMInAgjODyeq-ZBeb3NvAnkzkew',
    appId: '1:203022293738:web:3177045eed2ef098f99593',
    messagingSenderId: '203022293738',
    projectId: 'invoices-beta',
    authDomain: 'invoices-beta.firebaseapp.com',
    storageBucket: 'invoices-beta.appspot.com',
    measurementId: 'G-13PWEYY1E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo0l-ARWX8mt7kJyFZcUbgvokR41Rb5lc',
    appId: '1:203022293738:android:ca082d1852b1813af99593',
    messagingSenderId: '203022293738',
    projectId: 'invoices-beta',
    storageBucket: 'invoices-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDszLxWAn7mzEB6W1FmAeGO9MYK0FmCMgg',
    appId: '1:203022293738:ios:ada65e2313276324f99593',
    messagingSenderId: '203022293738',
    projectId: 'invoices-beta',
    storageBucket: 'invoices-beta.appspot.com',
    iosBundleId: 'com.example.invoicesBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDszLxWAn7mzEB6W1FmAeGO9MYK0FmCMgg',
    appId: '1:203022293738:ios:e6fae41a494916caf99593',
    messagingSenderId: '203022293738',
    projectId: 'invoices-beta',
    storageBucket: 'invoices-beta.appspot.com',
    iosBundleId: 'com.example.invoicesBeta.RunnerTests',
  );
}
